[project]
name = 'Decentralized-Collaborative-Research-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.funding-contract]
path = 'contracts/funding-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-contract]
path = 'contracts/project-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
